apiVersion: v1
kind: Service
metadata:
  name: api-svc
  annotations:
  cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: api
  ports:
    - port: 80
      targetPort: 80
      name: http
  type: NodePort