apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  annotations:
    networking.gke.io/managed-certificates: "api-cert"
spec:
  rules:
  - host: api.6cloud.com.br
    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
            name: api-svc
            port:
              number: 80